sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t abhikrr/docker-react -f Dockerfile.dev .

script:
  - docker run abhikrr/docker-react npm run test -- --coverage